name: Frontend Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print test message
        run: echo "Frontend workflow trigger test success"